theketchio/ketch

- install.sh
> ketch cli install script

- README.md
- ci/README.md
This PR includes Readme file update for Ketch v0.1.1 release
> update readme for v0.1.1 release

- ROADMAP.md
Updated `ROADMAP.md` to reflect new v0.2.0 release date of Jan 2021.
> update v0.2.0 release date

- cmd/ketch/app.go
- cmd/ketch/app_info.go
- cmd/ketch/app_info_test.go
- cmd/ketch/app_list.go
- cmd/ketch/app_test.go
- cmd/ketch/labels.go
- cmd/ketch/testdata/app-info/go-app-secret-name.output
- cmd/ketch/testdata/app-info/go-app.output
- internal/api/v1beta1/app_types.go
Updates output of `app list` and `app info` commands, replacing column `UNITS` with `STATUS`.
> [SHIPA-814] app status

- cmd/ketch/app.go
- cmd/ketch/app_log.go
- cmd/ketch/app_log_test.go
- cmd/ketch/errors.go
- cmd/ketch/testdata/app-log/1.output
- cmd/ketch/testdata/app-log/2.output
- cmd/ketch/testdata/app-log/3.output
- cmd/ketch/testdata/app-log/4.output
- cmd/ketch/testdata/app-log/stream-1.output
- cmd/ketch/testdata/app-log/stream-2.output
This PR adds `ketch app log` command to stream logs of an application
> Add app log command to stream logs of an application

- cmd/ketch/pool_add.go
- internal/chart/testdata/charts/dashboard-traefik-cluster-issuer.yaml
- internal/templates/traefik/yamls/certificate.yaml
Fixes https://shipaio.atlassian.net/browse/SHIPA-970
I fixed this issue in the PR   and it seems working as expected.
Since we were changing all the routing configs for Traefik as well as Istio in ketch canary PR, so I targeted the ketch canary branch for this PR.Now a user will have to follow similar steps as istio for Traefik as well because of the changes in the new Traefik versions.For example:
- Cert-Manager If not already present in your cluster, you can install cert-manager by using the following commands:
```
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.3/cert-manager.yaml
```
- Cluster Issuer
If not already present in your cluster, you can install a cluster issuer by creating the cluster-issuer-traefik.yaml file with the …
> [SHIPA-970] fix Tls issues with Traefik 2.x

- internal/docker/docker.go
> Fix docker client version bug

- cmd/ketch/app_deploy.go
- cmd/ketch/app_deploy_test.go
- Added some extra checks and improvements 
- steps normalization added so that traffic always reaches 100%
- limits over steps added
> [Shipa 723] ketch canary improvements

- cmd/ketch/app_deploy.go
- cmd/ketch/app_deploy_test.go
- cmd/ketch/testdata/Procfile
- cmd/ketch/testdata/mini-ketch.yaml
- config/crd/bases/theketch.io_apps.yaml
- internal/api/v1beta1/app_types.go
- internal/build/build.go
- internal/build/build_context.go
- internal/build/build_test.go
- internal/controllers/app_controller.go
- internal/docker/docker.go
- internal/docker/docker_test.go
This commit does the following:
* validate of arguments of "ketch app deploy" command before building
an image
* for deployment from source, there are several ways to provide
Procfile and ketch.yaml: in the given source directory and with
--procfile and --ketch-yaml flags.
> Optimization of app deploy

- internal/chart/testdata/charts/dashboard-istio-cluster-issuer.yaml
- internal/chart/testdata/charts/dashboard-istio.yaml
- internal/templates/istio/yamls/gateway.yaml
- internal/templates/istio/yamls/virtualService.yaml
> Fix istio templates: http gateway port must be 80

- cmd/ketch/cluster_issuer.go
- cmd/ketch/configuration/configuration.go
- cmd/ketch/errors.go
- cmd/ketch/pool_add.go
- cmd/ketch/pool_add_test.go
- cmd/ketch/pool_update.go
- cmd/ketch/pool_update_test.go
- cmd/ketch/root.go
- internal/mocks/configuration.go
> Pool create/update with invalid cluster-issuer should report error

- cmd/ketch/app_deploy.go
- cmd/ketch/app_deploy_test.go
- cmd/ketch/app_info.go
- cmd/ketch/testdata/app-info/go-app-secret-name.output
- cmd/ketch/testdata/app-info/go-app.output
- Show weights for the deployments for an app
- Improve app deploy output
> Show canary weight with app info

- cmd/ketch/app_info.go
- cmd/ketch/testdata/app-info/go-app-secret-name.output
- cmd/ketch/testdata/app-info/go-app.output
> Shipa 1027 minor fix: Weight ---> WEIGHT

- cmd/ketch/app_deploy.go
- cmd/ketch/app_deploy_test.go
- config/crd/bases/theketch.io_apps.yaml
- internal/api/v1beta1/app_types.go
- internal/controllers/app_controller.go
- internal/controllers/constants.go
Fixes  https://shipaio.atlassian.net/browse/SHIPA-1026
> [Shipa-1026]

- README.md
> changed the controller version

- README.md
> Update istio install instructions

- README.md
- ROADMAP.md
> Getting involved and officer hours doc update

- config/crd/bases/theketch.io_apps.yaml
- internal/api/v1beta1/app_types.go
Corrects an improperly capitalized json struct tag.
> corrects casing of framework tag

- README.md
> Updated README with 0.3.0 release updates

- internal/chart/application_chart.go
- internal/chart/application_chart_test.go
- internal/chart/process.go
- internal/chart/testdata/charts/dashboard-istio-cluster-issuer.yaml
- internal/chart/testdata/charts/dashboard-istio.yaml
- internal/chart/testdata/charts/dashboard-traefik-cluster-issuer.yaml
- internal/chart/testdata/charts/dashboard-traefik.yaml
> Bugfix: process envs were not injected to a container

- internal/chart/procfile.go
> Remove unused WriteProcfile and AssertProcfileNotExist funcs

- config/crd/bases/theketch.io_apps.yaml
- internal/api/v1beta1/app_types.go
- internal/chart/application_chart.go
- internal/chart/application_chart_test.go
- internal/chart/testdata/charts/dashboard-istio-cluster-issuer.yaml
- internal/chart/testdata/charts/dashboard-istio.yaml
- internal/chart/testdata/charts/dashboard-traefik-cluster-issuer.yaml
- internal/chart/testdata/charts/dashboard-traefik.yaml
- internal/deploy/yaml.go
- internal/templates/common/yamls/deployment.yaml
> Define imagePullSecrets per application deployment

- config/crd/bases/theketch.io_apps.yaml
- internal/api/v1beta1/app_types.go
- internal/chart/application_chart.go
- internal/chart/application_chart_test.go
- internal/chart/process.go
- internal/chart/process_test.go
- internal/chart/testdata/charts/dashboard-istio-cluster-issuer.yaml
- internal/chart/testdata/charts/dashboard-istio.yaml
- internal/chart/testdata/charts/dashboard-traefik-cluster-issuer.yaml
- internal/chart/testdata/charts/dashboard-traefik.yaml
- internal/templates/common/yamls/deployment.yaml
Extend App CRD with volumes and volumeMounts.
Fixes # 1873
> Shipa 1873

- cli_tests/app.sh
- cli_tests/install_ketch.sh
- cmd/ketch/framework.go
- cmd/ketch/framework_add.go
- cmd/ketch/framework_update.go
- cmd/manager/main.go
- internal/api/v1beta1/framework_types.go
- internal/chart/application_chart_test.go
- internal/chart/testdata/charts/dashboard-nginx-cluster-issuer.yaml
- internal/chart/testdata/charts/dashboard-nginx.yaml
- internal/controllers/framework_controller_test.go
- internal/templates/generator/main.go
- internal/templates/nginx/yamls/certificate.yaml
- internal/templates/nginx/yamls/ingress.yaml
- internal/templates/storage.go
Add support for Nginx ingress controller
To test, install nginx 
```
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update
helm install ingress-nginx ingress-nginx/ingress-nginx
```
Add nginx framework
```
ketch framework add fw2-nginx --ingress-type nginx --ingress-service-endpoint {ip of nginx service}
```
Deploy app
```
ketch app deploy go1 -i shipasoftware/go-app:v1 -k fw1-nginx
```
> [SHIPA-1866] Introduce nginx ingress controller

- cli_tests/install_ketch.sh
- internal/chart/testdata/charts/dashboard-nginx-cluster-issuer.yaml
- internal/chart/testdata/charts/dashboard-nginx.yaml
- internal/templates/nginx/yamls/ingress.yaml
- fix integration tests helm cli install
- modify nginx ingress to align for v1 version
> Fix networking v1 ingress

- internal/chart/testdata/charts/dashboard-istio-cluster-issuer.yaml
- internal/chart/testdata/charts/dashboard-istio.yaml
- internal/chart/testdata/charts/dashboard-nginx-cluster-issuer.yaml
- internal/chart/testdata/charts/dashboard-nginx.yaml
- internal/chart/testdata/charts/dashboard-traefik-cluster-issuer-shipa.yaml
- internal/chart/testdata/charts/dashboard-traefik-cluster-issuer.yaml
- internal/chart/testdata/charts/dashboard-traefik.yaml
- internal/templates/common/yamls/deployment.yaml
- internal/templates/common/yamls/gateway_service.yaml
- internal/templates/common/yamls/service.yaml
- internal/templates/istio/yamls/certificate.yaml
- internal/templates/istio/yamls/gateway.yaml
- internal/templates/istio/yamls/virtualService.yaml
- internal/templates/job/yamls/job.yaml
- internal/templates/nginx/yamls/certificate.yaml
- internal/templates/nginx/yamls/ingress.yaml
- internal/templates/traefik/yamls/certificate.yaml
- internal/templates/traefik/yamls/ingressroute.yaml
Some label and annotation fields could be troublesome if someone named and app or process 'true' or '45'. Use more quotes. 
Fixes # [1974](https://shipaio.atlassian.net/browse/SHIPA-1974?atlOrigin=eyJpIjoiMmU0ZTc2ZmI0MzQwNGU4MmI3ZGRlMjMyNWRlOTY3ZTciLCJwIjoiaiJ9)
> [SHIPA-1974] Adds quotes to label & annotation values

- config/rbac/role.yaml
- internal/controllers/app_controller.go
> Fix RBAC role: add permissions to manage DestinationRules

- internal/chart/testdata/charts/dashboard-istio-cluster-issuer.yaml
- internal/chart/testdata/charts/dashboard-nginx-cluster-issuer.yaml
- internal/chart/testdata/charts/dashboard-nginx.yaml
- internal/chart/testdata/charts/dashboard-traefik-cluster-issuer-shipa.yaml
- internal/chart/testdata/charts/dashboard-traefik-cluster-issuer.yaml
- internal/templates/istio/yamls/gateway.yaml
- internal/templates/nginx/yamls/ingress.yaml
- internal/templates/traefik/yamls/https-ingress-routes.yaml
> [SHIPA-2013] Add https redirect for all ingress controllers

- internal/chart/application_chart_test.go
- internal/chart/testdata/charts/dashboard-traefik-cluster-issuer-shipa.yaml
- internal/chart/testdata/charts/dashboard-traefik-cluster-issuer.yaml
- internal/chart/testdata/charts/dashboard-traefik.yaml
- internal/templates/traefik/yamls/http-ingress-route.yaml
- internal/templates/traefik/yamls/https-ingress-routes.yaml
> Apply app.spec.annotations to traefik IngressRoute

- ROADMAP.md
> Updated Roadmap

- .github/workflows/deploy.yaml
- .github/workflows/release.yaml
- README.md
Rm travis build badge and add GHActions. It sounds like the workflow name needs to match the filename (https://andresand.medium.com/adding-github-action-workflow-status-badge-to-your-repository-22ccea025af6)
> Update readme and gh action workflow names

- config/rbac/role.yaml
- internal/controllers/app_controller.go
> Add traefik 2 middlware role

- config/manager/manager.yaml
- internal/controllers/app_controller_test.go
Controller keeps crashing often when multiple apps are deployed over shipa
> Increase ketch controller limits

- config/manager/manager.yaml
> Remove manager limits

- internal/controllers/job_controller.go
- internal/controllers/job_controller_test.go
Previously, if ketch controller was being restarted and somebody
deleted a job CR, the corresponding helm chart was not deleted because
ketch didn't get DELETE event.
> Set ketch-controller as finalizer for Job CR

- internal/templates/job/yamls/job.yaml
I noticed `completions` weren't working as expected during some experimentation. Bug squashed.
> Fixes completions field for jobs

- ci/limits.json
> Lower unit test coverage for the additional types from main rebase

- internal/controllers/framework_controller.go
> Add ExtensionsStatuses to FrameworkStatus

- internal/controllers/app_controller.go
- internal/controllers/app_controller_test.go
[SHIPA-2258](https://shipaio.atlassian.net/browse/SHIPA-2538?atlOrigin=eyJpIjoiYTc4MTY5ODExNjE2NDM4ZmJiYTc4NWNkNmI4YWMwMTEiLCJwIjoiaiJ9) 
Ketch uses `cli.k8sClient.CoreV1().Events(cli.workloadNamespace).Watch()` to watch for deployment changes and creates Ketch events when appropriate. When this function errors, the message can be unclear. It can cause downstream services like Shipa to fail/retry without any indication of what is actually happening. This `Watch()` function consistently errors with `unknown (get events)` when clusterrole "manager-role" is missing "watch" permission on "resources".  
This PR does 2 things:
- Creates an `AppReconcileError` event when the watcher fails to run
- Looks for the enigmatic `unknown (get events)` error (which is from k8s.io) and annotates it
TEST …
> [SHIPA-2258] Annotate unknown(get event) error during watch

- internal/controllers/app_controller.go
Reverts part of a change from a previous PR. Len is checked in the clause above this one.
> Remove superflous len(deployments) check

- cmd/manager/main.go
- config/crd/bases/theketch.io_jobs.yaml
- config/rbac/role.yaml
- internal/api/v1beta1/job_types.go
- internal/chart/job_chart_test.go
- internal/chart/testdata/render_yamls/annotations-patch.yaml
- internal/controllers/job_controller.go
- internal/controllers/job_controller_test.go
- internal/templates/cronjob/yamls/cronjob.yaml
- internal/templates/generator/main.go
- internal/templates/job/yamls/job.yaml
- internal/templates/storage.go
- internal/templates/storage_test.go
[SHIPA-2940] Adds Cronjob support. After discussing w/ Aleksej, I decided to extend the `Jobs CRD` rather than create a unique `CronJob CRD`. We were 50/50 on this decision, so I'm open to input preferring a `CronJob CRD`. 
Adds Cron-specific fields to `JobSpec`. Creates a K8s `CronJob` resource if the `schedule` string is populated. There is already a webhook assuring that 2 `jobs` do not have the same name. 
**Testing:**
Be sure to uninstall and `make generate manifest install` before running ketch.
`k apply -f cronjob.yaml`
`ketch job list`
`k get cronjobs -A`
sample yaml:
```
apiVersion: theketch.io/v1beta1
kind: Job
metadata:
name: testcron
spec:
name: testcron
type: Job
framework: test
description: 'a test cron job - ketch'
schedule: '* * * * *'
containers:
- name: list
image: …
```
> [SHIPA-2940] Add CronJob to ketch jobs

- config/crd/bases/theketch.io_apps.yaml
With recent changes in the HealthCheck model, We should update ketch's CRDs with `make generate manifests` command
> [SHIPA-2893] Generate manifests for new ketch healthcheck model

- config/rbac/role.yaml
- internal/controllers/app_controller.go
Add missing permissions for network policies, configmaps and deployments
> Add missing permissions

- config/rbac/role.yaml
- internal/controllers/app_controller.go
Add explicit replicaset role for ketch helm package
> Add replica set role

- config/rbac/role.yaml
- internal/controllers/app_controller.go
> Add autoscaling role

- config/rbac/role.yaml
- internal/controllers/app_controller.go
Add persistentvolumeclaims resource CRUD permission
> [PLAY-138] Add persistent volume claim role

- config/rbac/role.yaml
- internal/controllers/app_controller.go
Add pods/exec permission to allow exec into app
> Add pods/exec and persistentvolume permission

- internal/chart/testdata/charts/dashboard-istio-cluster-issuer-pod-security-context.yaml
- internal/chart/testdata/charts/dashboard-istio-cluster-issuer-volume-claim-templates.yaml
- internal/chart/testdata/charts/dashboard-istio-cluster-issuer.yaml
- internal/chart/testdata/charts/dashboard-istio.yaml
- internal/chart/testdata/charts/dashboard-nginx-cluster-issuer.yaml
- internal/chart/testdata/charts/dashboard-nginx.yaml
- internal/chart/testdata/charts/dashboard-traefik-cluster-issuer-shipa.yaml
- internal/chart/testdata/charts/dashboard-traefik-cluster-issuer.yaml
- internal/chart/testdata/charts/dashboard-traefik.yaml
- internal/templates/common/yamls/deployment.yaml
- internal/templates/common/yamls/gateway_service.yaml
- internal/templates/common/yamls/service.yaml
- internal/templates/common/yamls/stateful_set.yaml
- internal/templates/cronjob/yamls/cronjob.yaml
- internal/templates/istio/yamls/certificate.yaml
- internal/templates/istio/yamls/destinationRule.yaml
- internal/templates/istio/yamls/gateway.yaml
- internal/templates/istio/yamls/virtualService.yaml
- internal/templates/job/yamls/job.yaml
- internal/templates/nginx/yamls/certificate.yaml
- internal/templates/nginx/yamls/ingress.yaml
- internal/templates/traefik/yamls/certificate.yaml
- internal/templates/traefik/yamls/http-ingress-route.yaml
- internal/templates/traefik/yamls/https-ingress-routes.yaml
> add recommended labels

- internal/chart/testdata/charts/dashboard-nginx-cluster-issuer.yaml
- internal/chart/testdata/charts/dashboard-nginx.yaml
- internal/templates/nginx/yamls/ingress.yaml
> [PLAY-427] fix: CNAME with alias *.foo.bar breaks ketch controller

- cli_tests/app.sh
> fix: image source

- internal/controllers/app_controller.go
- internal/controllers/app_controller_test.go
> [PLAY-662] fix: use latest hpa version

- .github/workflows/build.yaml
Push to ECR registry alongside dockerhub
> [PLAY-679] Push to ECR alongside Dockerhub

- internal/api/v1beta1/app_types.go
- internal/api/v1beta1/app_types_test.go
- internal/chart/application_chart.go
- internal/chart/application_chart_test.go
- internal/chart/process.go
- internal/chart/testdata/charts/dashboard-nginx-hpa.yaml
- internal/controllers/app_controller.go
- internal/controllers/app_controller_test.go
- internal/templates/common/yamls/deployment.yaml
If HPA is present, then use HPA currentReplicas for Deployment replicas
> Play 761 correct replicas with hpa
