Makefile
Changed hardcoded Kubebuilder release name to use env vars that detect user operating system and system architecture.
=> Detect os and arch to download correct kubebuilder binary

cmd/ketch/app_export_test.go, go.mod, go.sum, internal/chart/application_chart.go
https://shipaio.atlassian.net/browse/SHIPA-808
Currently, ketch wipes all the data of the directory before exporting a chart that we pass with ketch app export cmd. This wiping of all data from a parent dir could cause a lot of serious problems. For example, if the user sets the directory path to `/Users/username` it will wipe all data inside it.
My proposal to fix it:
- on ketch export, make a folder with `appName_TIMESTAMP` inside the user-provided path and save the exported chart data inside it to keep parent dir safe.
- With this approach, a user could save multiple app charts inside a parent dir.
- timestamp can help them to identify the latest one
- user will not lose the older charts
=> [SHIPA-808] make dir with app name for saving chart with export cmd

.travis.yml
Currently Ketch build job uses PR branch name as docker image tag:
https://github.com/shipa-corp/ketch/blob/161c4ba2ec41c45bf72667aaa2c980ded1495225/.travis.yml#L28
This causes docker build to fail when `$TRAVIS_PULL_REQUEST_BRANCH` contains a `/`. This PR uses the current commit (env var `$TRAVIS_COMMIT`) instead of PR branch for image tag.
=> use commit for travis image name

cmd/ketch/app_create.go, cmd/ketch/app_create_test.go
This PR introduces a check for pool validity with `app create` .
Prior to this PR Ketch did not check existence of pool passed in with `app create`, resulting in the ability to create applications with invalid pools.  Although an invalid or nonexistent pool would be detected with `app deploy`, catching this issue as early as possible (with `app create`) improves UX. 
Fixes #34
- Added test to ensure app is not created if invalid pool is passed to `app create`
=> Check if pool exists before creating app

cmd/ketch/pool_remove.go, cmd/ketch/pool_remove_test.go, go.mod, go.sum
Kubebuilder does not remove namespaces with the deletion of Kubernetes objects, even if the namespace is empty.  This PR introduces three additional client calls to the `poolRemove` function:
1. Get the pool-to-be-removed so we have access to its namespace (only have pool name with cli args)
2. Get the namespace associated with the pool-to-be-removed
3. Remove the associated namespace
While I did write a test, I did not include it here.  The [fake client](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client/fake#ClientBuilder) included with Kubebuilder does not alter cluster namespace when creating a pool, so `poolRemove` fails with `failed to get namespace`.  I had a test that ignores this error, but it defeats the purpose of testing IMO so I left it out.
I did come across …
=> remove namespace with pool remove command

internal/docker/auth.go, internal/docker/auth_integration_test.go, internal/docker/docker.go
See [SHIPA-1022](https://shipaio.atlassian.net/browse/SHIPA-1022?atlOrigin=eyJpIjoiODhiM2UwY2ZkZDU2NGIyZmJjZTVlMjI4NDE3MDlhZjgiLCJwIjoiaiJ9). Ketch uses the same mechanism to obtain registry authentication credentials as the Docker CLI.  It relies on the Docker CLI being present in order to deploy applications from source. Docker needs to shell out to an operating system specific helper function that retrieves auth credentials from secret storage for the OS, for example, the keychain on the Mac. We were not handling that correctly.
=> [SHIPA-1022] Registry Auth fails on Mac

cmd/ketch/platform.go, cmd/ketch/platform_test.go
Ketch was hanging on start up because operations associated with platform were attempting to connect to a k8s cluster when the application started.  I fixed this by deferring the k8s connection until the cluster was actually needed, which would be after initialization.  
Fixes # [SHIPA-1021](https://shipaio.atlassian.net/browse/SHIPA-1021?atlOrigin=eyJpIjoiZTY2ZmJkZGYzYTBhNGNkODkwM2ZlNjk4YzU2M2ZlMTQiLCJwIjoiaiJ9)
=> [SHIPA-1021] Fix Ketch Hanging on Start Up

config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml
We use gcr.io/distroless/static:nonroot image as a base image for ketch
controller and we have to explicitly define uid and gid to be able to use
RunAsNonRootUser: true.
https://github.com/GoogleContainerTools/distroless/blob/master/base/testdata/base.yaml#L40
=> Hardening ketch controller deployment

internal/chart/application_chart.go, internal/chart/application_chart_test.go, internal/chart/configurator.go, internal/chart/configurator_test.go
Minimal images do not have a shell and this breaks the pod command construction which requires a shell for build hooks.  This is fixed by skipping this step if there is not a platform defined. 
Fixes Subtask [shipa-1131](https://shipaio.atlassian.net/browse/SHIPA-1131)
- [x ] New tests were added with this PR that prove my fix is effective or that my feature works (describe below this bullet)
=> [SHIPA-1131] Fix app deploy for minimal images

cmd/ketch/app.go, cmd/ketch/app_deploy.go, cmd/ketch/app_deploy_test.go, cmd/ketch/builder.go, cmd/ketch/builder_set.go, cmd/ketch/builder_set_test.go, cmd/ketch/configuration/configuration.go, cmd/ketch/root.go, internal/deploy/parameters.go
Allow for the user to set their own default builder to be used whenever a new application is created from source. The name of the builder is persisted via a config.toml. The default location of the config.toml is expected to be `~/.ketch/`, but this can be overwritten by exporting the path to config.toml as `KETCH_HOME`
Fixes #1461
=> Shipa 1461 set default builder

cli_tests/app.sh, cmd/ketch/app_deploy.go, cmd/ketch/app_info.go, cmd/ketch/framework_add_test.go, cmd/ketch/framework_export_test.go, cmd/ketch/framework_list_test.go, cmd/ketch/framework_update_test.go, internal/api/v1beta1/framework_webhook_test.go, internal/chart/procfile.go, internal/controllers/app_controller_test.go, internal/controllers/framework_controller_test.go, internal/deploy/deploy.go, internal/deploy/parameters.go, internal/deploy/yaml.go, internal/deploy/yaml_test.go, internal/testutils/utils.go, internal/utils/conversions/conversions.go
Adds basic handling of app.yaml files to deploy apps, e.g. `ketch app deploy app.yaml`. Note, the added integration test is a little crude. There is an open ticket to improve timeout/retries in integration tests. 
Fixes # SHIPA-1543
Spec: https://docs.google.com/document/d/1fMaLn7ViztU4L8nxV1sTFwLW3-64mWraOiOAE5MnlOw
_Example yaml (assumes you have ketch, traefik installed on a cluster and a framework called "myframework"):_
**app.yaml**
```
name: test
image: gcr.io/shipa-ci/sample-go-app:latest
framework: myframework
```
`ketch app deploy app.yaml`
The `--wait` and `--timeout` flags are functional when using a yaml. E.g. force a timeout `ketch app deploy app.yaml --wait --timeout 1s`. Or simply wait for app to become EventTypeNormal ketch app deploy app.yaml --wait `
Please include …
=> adds app yaml

.github/workflows/release.yaml
The Go version we use to cut releases (1.15.1) is out of sync with the version we use in CI (1.16). I'm running into newer stdlib functions that aren't available. 
Fixes # --
=> Use go 1.16 for releases

cli_tests/app.sh, cmd/ketch/app.go, cmd/ketch/app_export.go, cmd/ketch/app_export_test.go, cmd/ketch/framework.go, cmd/ketch/framework_add.go, cmd/ketch/framework_add_test.go, cmd/ketch/framework_export.go, cmd/ketch/framework_export_test.go, internal/deploy/yaml.go
- Adds `name` to `framework` when framework is created via cli args.
- defaults export commands to stdout, rather than yaml file
- adds omitempty on `application.version` in yaml pkg to prevent "version: null" when there is no version specified
Fixes # 1626
=> Export defaults to stdout + cleanup

.travis.yml, cli_tests/job.sh, cmd/ketch/app_export.go, cmd/ketch/auto_completion.go, cmd/ketch/errors.go, cmd/ketch/framework_export.go, cmd/ketch/framework_export_test.go, cmd/ketch/job.go, cmd/ketch/job_deploy.go, cmd/ketch/job_deploy_test.go, cmd/ketch/job_export.go, cmd/ketch/job_export_test.go, cmd/ketch/job_list.go, cmd/ketch/job_list_test.go, cmd/ketch/job_remove.go, cmd/ketch/job_remove_test.go, cmd/ketch/output/output.go, cmd/ketch/root.go, config/crd/bases/theketch.io_jobs.yaml, config/crd/kustomization.yaml, internal/api/v1beta1/job_types.go, internal/controllers/job_controller.go, internal/templates/job/yamls/job.yaml
Adds CLI commands `job deploy`, `job list`, `job export`, `job remove`. Job deploy only implements yaml file deployments. [Spec here](https://docs.google.com/document/d/1fMaLn7ViztU4L8nxV1sTFwLW3-64mWraOiOAE5MnlOw/edit#heading=h.6qrq7urqg756). Makes version, policy, and description fields optional. 
I also found some small fixes that were needed for the Job CRD, noted in comments.
Try it:
`make install ketch manager`
`./bin/manager --enable-leader-election=false --disable-webhooks` (assuming you're not deploying)
`./bin/ketch framework add fw`
`./bin/ketch job deploy job.yaml`
`k get jobs -n ketch-fw`
`k get pods -n ketch-fw`
`k logs <pod> - n ketch-fw pi` 
`./bin/ketch job export myjob`
`./bin/ketch job list`
`./bin/ketch job remove myjob`
example *job.yaml*:
```
name: myjob
version: v1 …
```
=> Job CLI deploy/list/export/remove

install.sh
This simple fix enables ketch installation on apple m1 machines. I tested, it works well as apple m1 allows running darwin-amd64 binaries via rosetta2 automatically.
=> install ketch CLI on apple m1 machines

cli_tests/job.sh, cmd/ketch/job_deploy.go
`Job` completions value should default to the parallelism value if unset (per discussion w/ Vivek and K8s Job docs). Adds an integration test that asserts that `Job` `completions` and `parallelism` values are as expected.
Fixes # [1865](https://shipaio.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=SHIPA&modal=detail&selectedIssue=SHIPA-1865) - this is the **3rd item** listed in this issue.
=> Default Job completions to parallelism and add acceptance test

cli_tests/app.sh, cmd/ketch/framework_add.go
The error message to the user when trying to create a framework that already exists is unclear. This PR just checks the error and displays a clearer message. Adds test. If there's a better way to clarify errors generated by webhooks, let me know. 
This is the first item in issue below: 
Fixes # [1865](https://shipaio.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=SHIPA&modal=detail&selectedIssue=SHIPA-1865)
=> Clarify error message to user when framework already exists

cmd/ketch/job_deploy.go, cmd/manager/main.go, config/webhook/manifests.yaml, internal/api/v1beta1/errors.go, internal/api/v1beta1/job_webhook.go, internal/api/v1beta1/job_webhook_test.go
This is the 2nd item from the issue. Adds a webhook that prevents adding/updating a Job when a Job of the same name exists. Adds tests. Adds some user-friendly error text to the CLI. 
Fixes # [1865](https://shipaio.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=SHIPA&modal=detail&selectedIssue=SHIPA-1865)
=> Prevents deploying a Job when Job already exists

config/crd/bases/theketch.io_apps.yaml, internal/api/v1beta1/app_types.go
This PR fixes the following:
```bash
$ k get apps.theketch.io
NAME    FRAMEWORK   DESCRIPTION
myapp               
```
It should be 
```bash
$ k get apps.theketch.io
NAME    FRAMEWORK   DESCRIPTION
myapp    <framework>             
```
=> Fix framework column in "kubectl get apps.theketch.io"

internal/api/v1beta1/app_types.go, internal/api/v1beta1/app_types_test.go, internal/api/v1beta1/job_types.go, internal/controllers/app_controller.go, internal/controllers/job_controller.go, internal/templates/storage_test.go
Remove ketch imports from internal/api/v1beta1 package, so the types can be used independently without importing ketch itself
=> Remove ketch imports from internal/api/v1beta1 package

config/crd/bases/theketch.io_apps.yaml, internal/api/v1beta1/ketch_yaml.go
This PR removes the unused "build" section from `ketch.yaml`. After introducing buildpacks this section is not used.
=> Remove unused "build" section from ketch.yaml

cmd/ketch/configuration/configuration.go, cmd/manager/main.go, internal/api/v1beta1/app_types.go, internal/api/v1beta1/framework_types.go, internal/api/v1beta1/groupversion_info.go, internal/api/v1beta1/job_types.go, internal/chart/application_chart.go, internal/chart/application_chart_test.go, internal/chart/testdata/charts/dashboard-istio.yaml, internal/chart/testdata/charts/dashboard-traefik-cluster-issuer-shipa.yaml, internal/chart/testdata/charts/dashboard-traefik-cluster-issuer.yaml, internal/controllers/suite_test.go, internal/mocks/configuration.go, internal/templates/common/yamls/deployment.yaml, internal/templates/common/yamls/service.yaml, internal/templates/istio/yamls/gateway.yaml, internal/templates/istio/yamls/virtualService.yaml, internal/templates/traefik/yamls/ingressroute.yaml
Makes app's labels configurable with `--group`.
My editor's linter cleaned up a few stray spaces.
Fixes # [1889](https://shipaio.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=SHIPA&modal=detail&selectedIssue=SHIPA-1889)
=> Uses Group as prefix for apps' labels

config/crd/bases/theketch.io_frameworks.yaml, internal/api/v1beta1/framework_types.go, internal/controllers/framework_controller.go, internal/controllers/framework_controller_test.go
Extend Framework CRD to include annotations and labels. Make sure that these labels and annotations are added to the namespace and that ones not present in the newest framework aren't included.
To test install ketch using this branch and create a framework. Add annotations/labels with `kubectl edit framework`, after saving and exiting confirm the annotations/labels have also been added to the corresponding namespace by running `kubectl describe namespace <namespace-name>`. This process can be repeated any number of times to see how changes in the framework affect the corresponding namespace.
Fixes # 1875
=> Shipa 1875

cmd/ketch/app_info_test.go, cmd/ketch/app_list_test.go, cmd/ketch/cname_add.go, cmd/ketch/cname_remove.go, cmd/ketch/errors.go, config/crd/bases/theketch.io_apps.yaml, internal/api/v1beta1/app_types.go, internal/api/v1beta1/app_types_test.go, internal/chart/application_chart.go, internal/chart/application_chart_test.go, internal/deploy/deploy.go, internal/deploy/parameters.go, internal/deploy/yaml.go, internal/deploy/yaml_test.go
Makes the http/https scheme configurable per Cname. Switches `app.ingress.cnames` from `[]string` to `[]Cname{Name: <string>, Secure: <bool>}`. 
This change is backward compatible with:
- Using the CLI. Cnames were added with the `ketch cname add` command. I added a `--secure` flag. It will return a user error if you specify `secure` and the app's framework does not have a clusterIssuer. 
- Using app.yamls. Deploying a ketch app by yaml only permits **one** cname (probably worth changing in a new issue). I added a `secure` field to the `cname` object. 
```
cname:
dnsName: secure.10.96.13.219.shipa.cloud
secure: true
```
It will return user error if you specify `secure` and a framework without a cluster issuer. 
This PR changes what users will supply in a kubernetes config file. Cnames are …
=> [SHIPA-1943] Makes CName schemes configurable

.travis.yml
It would be great to be able to use ketch's image built from `main` branch
=> Build ketch:<commit> image

internal/chart/testdata/charts/dashboard-istio-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-istio.yaml, internal/chart/testdata/charts/dashboard-traefik-cluster-issuer-shipa.yaml, internal/chart/testdata/charts/dashboard-traefik-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-traefik.yaml, internal/templates/common/yamls/deployment.yaml, internal/templates/common/yamls/gateway_service.yaml, internal/templates/common/yamls/service.yaml
Helm fails to validate the metadata section of a k8s resource
if there is a label or annotations without quotes like in the following example
apiVersion: apps/v1
kind: Deployment
metadata:
annotations:
name: true
=> Put values of annotations and labels in quotes

config/crd/bases/theketch.io_apps.yaml, internal/api/v1beta1/app_types.go, internal/api/v1beta1/app_types_test.go, internal/controllers/app_controller.go
Scale process' units based on the current weight of deployment and specified target values per process. The `Target` map has been added to the `CanarySpec`, which is used to specify the target number of units per process. During the canary deployment, the two deployments' processes should add up to the target value (per process). The final deployment should have the same value as the target (per process).
In the previous deployment, if a process is not present in the target, the number of units will not be affected during the canary deployment, but will end up being removed (along with the rest of the deployment) if the canary deployment successfully completes.
In the updated deployment, if a process is not present in the target list, the process will be given a default value of 1.
To …
=> Scale target deployment for canary

config/crd/bases/theketch.io_apps.yaml, internal/api/v1beta1/app_types.go, internal/chart/application_chart.go, internal/chart/application_chart_test.go, internal/chart/process.go, internal/chart/testdata/charts/dashboard-istio-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-istio.yaml, internal/chart/testdata/charts/dashboard-nginx-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-nginx.yaml, internal/chart/testdata/charts/dashboard-traefik-cluster-issuer-shipa.yaml, internal/chart/testdata/charts/dashboard-traefik-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-traefik.yaml, internal/templates/common/yamls/_helpers.tpl, internal/templates/common/yamls/deployment.yaml, internal/templates/common/yamls/service.yaml, internal/templates/istio/yamls/destinationRule.yaml, internal/templates/istio/yamls/gateway.yaml, internal/templates/istio/yamls/virtualService.yaml
This PR adds a DestinationRule in a way that istio time series will have `destination_app=<app.spec.id or app.name>` label
=> Add app.spec.id and DestinationRule for istio resources of app

config/crd/bases/theketch.io_apps.yaml, internal/api/v1beta1/app_types.go, internal/chart/application_chart_test.go, internal/chart/ingress.go, internal/chart/ingress_test.go, internal/chart/testdata/charts/dashboard-istio-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-istio.yaml, internal/chart/testdata/charts/dashboard-nginx-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-nginx.yaml, internal/chart/testdata/charts/dashboard-traefik-cluster-issuer-shipa.yaml, internal/chart/testdata/charts/dashboard-traefik-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-traefik.yaml, internal/templates/istio/yamls/certificate.yaml, internal/templates/nginx/yamls/certificate.yaml, internal/templates/traefik/yamls/certificate.yaml
This PR adds a new `secretName` field to Ketch App CRD. If provided, ketch doesn't obtain an SSL certificate for such a cname but expects that a given secret contains a valid SSL certificate. 
```yaml
spec:
ingress:
cnames:
- name: app.shipa.io
secure: true
- name: dashboard.shipa.io
secretName: my-secret
secure: true
```
=> [SHIPA-1944] Provide way to use user's SSL certificate for cnames

Makefile
Makefile: use `go install` instead of `go get`.
`go get` has been deprecated when installing binary.
https://golang.org/doc/go-get-install-deprecation
=> Makefile: use go install instead of go get

cmd/ketch/framework_remove.go, cmd/ketch/framework_remove_test.go
Deleting a framework and it's apps simultaneously, e.g. terraform, script, etc. can occasionally create a situation where an app is removed, but is still in the framework's `framework.Status.Apps` list. This can cause frustration since a user cannot remove the framework ("contains running apps" error) nor can they remove the already-removed app. This PR prunes non-existent apps from the `framework.Status.Apps` list prior to the framework delete.
Fixes # [2024](https://shipaio.atlassian.net/browse/SHIPA-2024?atlOrigin=eyJpIjoiYTY1YjE3YjMyMzhiNGFjMmE0ZGU2MjA0NTJkODY5MTgiLCJwIjoiaiJ9)
=> [SHIPA-2024] Prunes dead apps from framework status when removing framework

config/crd/bases/theketch.io_apps.yaml, internal/api/v1beta1/app_types.go, internal/chart/application_chart.go, internal/chart/application_chart_test.go, internal/chart/testdata/charts/dashboard-nginx.yaml, internal/templates/common/yamls/deployment.yaml
=> Use user-provided service account

config/default/manager_webhook_patch.yaml
If cert-manager is not ready when ketch controller's pod is being
created, the pod hangs with the following error message:
MountVolume.SetUp failed for volume "cert" : secret "webhook-server-cert" not found
This commit
1. makes the secret optional, so if the secret is not ready,
the pod doesn't hang
2. ketch-controller will keep failing until the secret is ready
=> Gracefull handle cert-manager boot

config/rbac/role.yaml
Ketch needs to be able to watch/list events for the ketch/shipa integration to work. This should have been added to PR #177, but I must have accidentally removed it. 
=> Adds missing event verbs to ketch clusterrole

config/rbac/role.yaml, internal/controllers/app_controller.go
`make manifests` was removing `watch` and `list` from `events` rbac perms. _This_ will do the trick.
=> Adds missing rbac verbs to kubebuilder tags

.github/workflows/deploy.yaml, Makefile, ci/limits.json
Fixes # [2139](https://shipaio.atlassian.net/browse/SHIPA-2139?atlOrigin=eyJpIjoiODkxMDI0NjBlMWQ1NDhjZGFhNGM1OGFmNGVkMmEwMTgiLCJwIjoiaiJ9)
Relies on https://github.com/theketchio/unit-test-coverage, which I made public. `unit-test-coverage` may be used by our private shipa repos, but I figured it should be public as it is used by Ketch. This PR adds CI steps that run `unit-test-covreage` using `ci/limits.json`. In the event test coverage drops below the current level specified in limits.json, you'll get a failure and see output like this:
=> [SHIPA-2139] enforce unit test coverage

cmd/manager/main.go
With recent deployment monitoring, there can be lots more than 10 messages in a second
=> MaxInt for recorder burst size

internal/api/v1beta1/app_types.go, internal/api/v1beta1/app_types_test.go, internal/controllers/app_controller.go, internal/controllers/app_controller_test.go
If there is an HPA for an app, we do not want units to be scaled in canary deployment
Fixes # 2147
=> Prevent pod scaling if app is the target of an HPA

config/rbac/role.yaml, internal/controllers/app_controller.go
we use `networking.k8s.io` group to work with Ingress objects
=> Remove usage of extensions.ingress

ci/limits.json, internal/chart/helm_client.go
Currently, we don't specify MaxHistory and a number of helm releases
keeps growing meaning ketch creates lots of secrets named
`sh.helm.release.v1.<app-name>.v<version>`.
=> Keep only 1 historical helm release per app on cluster

internal/chart/testdata/charts/dashboard-istio-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-istio.yaml, internal/chart/testdata/charts/dashboard-nginx-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-traefik-cluster-issuer-shipa.yaml, internal/chart/testdata/charts/dashboard-traefik-cluster-issuer.yaml, internal/templates/istio/yamls/certificate.yaml, internal/templates/istio/yamls/destinationRule.yaml, internal/templates/nginx/yamls/certificate.yaml, internal/templates/traefik/yamls/certificate.yaml
Some of k8s resources of the app helm chart didn't have theketch.io/app-name label making it hard to query a cluster to get all app resources
=> Make sure all resources contain theketch.io/app-name label

internal/chart/testdata/charts/dashboard-istio-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-nginx-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-traefik-cluster-issuer-shipa.yaml, internal/chart/testdata/charts/dashboard-traefik-cluster-issuer.yaml, internal/templates/istio/yamls/certificate.yaml, internal/templates/nginx/yamls/certificate.yaml, internal/templates/traefik/yamls/certificate.yaml
Currently, all app resources except secrets created by cert-manager have `theketch.io/app-name` label. 
This PR forces cert-manager to create secrets with this label. 
https://cert-manager.io/docs/usage/certificate/#creating-certificate-resources
=> Add theketch.io/app-name label to secrets provisioning by cert-manager

config/crd/bases/theketch.io_apps.yaml, internal/api/v1beta1/app_types.go, internal/chart/application_chart_test.go, internal/chart/process.go, internal/chart/process_test.go, internal/chart/testdata/charts/dashboard-istio-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-istio.yaml, internal/chart/testdata/charts/dashboard-nginx-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-nginx.yaml, internal/chart/testdata/charts/dashboard-traefik-cluster-issuer-shipa.yaml, internal/chart/testdata/charts/dashboard-traefik-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-traefik.yaml, internal/templates/common/yamls/deployment.yaml, internal/templates/common/yamls/service.yaml
=> Use MetadataItems to set labels/annotations for pods

ci/limits.json, cmd/manager/main.go, internal/chart/helm_client.go
- set helm release secret status to Failed before doing helm update if release was created more than 10 minutes ago
- this should unblock next helm update of application
=> Fix helm update client forever blocked

cmd/manager/main.go, internal/chart/helm_client.go, internal/chart/helm_client_factory.go, internal/chart/helm_client_factory_test.go
we are not alone trying to find a workaround for the memory consumption
https://github.com/helm/helm/issues/10374
it looks like having a per-namespace cache for `action.Configuration` should help
(according to https://github.com/helm/helm/issues/10374#issuecomment-974242797 )
=> Use a cache when creating a new helm client to avoid initialization

internal/api/v1beta1/app_types.go, internal/controllers/app_controller.go, internal/controllers/app_controller_test.go
Previously, if ketch controller was being restarted and somebody
deleted an app CR, the corresponding helm chart was not deleted because
ketch didn't get DELETE event.
=> Set ketch-controller as finalizer for App CR

internal/controllers/app_controller.go, internal/controllers/app_controller_test.go, internal/controllers/job_controller.go
Ketch controller will eventually update an application CR and we are
good to print this type of errors to logs only.
=> Dont create events when ketch controller gets a conflict error

config/manager/manager.yaml
Ketch controller consumes 100m memory on average and uses 10-15m cpu. 
(measured with metrics-server)
=> Ketch controller to request 100m cpu and 300Mi memory

internal/chart/application_chart_test.go, internal/chart/testdata/charts/dashboard-istio-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-istio.yaml, internal/chart/testdata/charts/dashboard-nginx-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-nginx.yaml, internal/chart/testdata/charts/dashboard-traefik-cluster-issuer-shipa.yaml, internal/chart/testdata/charts/dashboard-traefik-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-traefik.yaml, internal/templates/common/yamls/deployment.yaml
Add heathcheks into deployment template
=> [shipa-2326] add heathcheks into deployment

internal/chart/chartutils_test.go, internal/chart/job_chart.go, internal/chart/job_chart_test.go, internal/templates/job/yamls/job.yaml
Sets the job-name label on `Job` resource dynamically. 
=> Dynamically sets job label w/ group name

CONTRIBUTING.md
Adds a section to CONTRIBUTING with the basic steps I take to run the Ketch Controller locally for debugging during development. 
Writing documentation always sounds easy, but is hard in practice - what should I include? Are they clear? Open to suggestions & additions.
=> Adds section To CONTRIBUTING on running controller locally

internal/api/v1beta1/annotations.go, internal/controllers/app_controller.go, internal/controllers/app_controller_test.go, internal/controllers/job_controller.go, internal/controllers/job_controller_test.go, internal/controllers/suite_test.go, internal/controllers/utils.go, internal/controllers/utils_test.go
Sometimes we want to remove App/Job CR but keep their helm chart
running, it is kind of soft self-uninstalling)
To handle this use-case, ketch-controller checks for
`theketch.io/dont-uninstall-helm-chart=true` annotation.
If it is present on an App/Job CR and kuberentes has marked the CR for deletion,
ketch controller doesn't uninstall its helm chart.
=> Add annotation to prevent uninstalling helm chart of Job/App

internal/chart/helm_client.go, internal/chart/helm_client_factory.go, internal/chart/helm_client_test.go
[2322](https://shipaio.atlassian.net/browse/SHIPA-2322?atlOrigin=eyJpIjoiMmRlYTJlNjM5M2M3NGMyMjkxMTg3MjNjMTc2YmFlOTgiLCJwIjoiaiJ9) 
Helm update and helm delete currently fail when the object status (app) is not `deployed`. This change checks a map for actionable & retryable statuses for updates and deletions. For wait-retry statuses, a wait-retry loop is entered, and ultimately the status is manually updated to `deployed`.
=> [SHIPA-2322] adds wait-retry to helm update & delete

config/crd/bases/theketch.io_apps.yaml, go.mod, go.sum
Several small improvements:
1. use containerd v1.5.10 and docker/distribution v2.8.0
2. Regenerate App CRD
=> Several small improvements

ci/limits.json, cmd/ketch/job_deploy.go, cmd/ketch/job_deploy_test.go, cmd/ketch/job_export_test.go, cmd/ketch/job_list_test.go, cmd/ketch/job_remove_test.go, config/crd/bases/theketch.io_jobs.yaml, internal/api/v1beta1/job_types.go, internal/api/v1beta1/job_types_test.go, internal/chart/chartutils_test.go, internal/chart/job_chart_test.go, internal/templates/job/yamls/job.yaml
Removes redundant `defaultBackoffLimit` from CLI. K8s sets the default to 6 when empty. Makes `backoffLimit` a pointer, permitting passing a `0` in. 
Fixes # shipa-2627
=> [SHIPA-2627] omit default backoffLimit value

internal/chart/testdata/charts/dashboard-nginx-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-nginx.yaml, internal/templates/nginx/yamls/ingress.yaml
Remove dependency on deprecated ingress.class annotation
Use ingressClassname spec field instead
=> Remove dependany on deprecated ingress class annotation

CONTRIBUTING.md, CONTRIBUTORS.md
=> Updated Contributor Guide and added Core Contributors 

internal/api/v1beta1/app_types.go, internal/controllers/app_controller.go, internal/controllers/app_controller_test.go
Shipa would like to emit app.error Shipa events when there is a deployment error via kubernetes. It would be helpful to have one of the offending pods for this. This PR uses the existing `getPodStatus` func to get the podName, which is then included in the K8s event as an annotation. 
Fixes # shipa-2788
=> [SHIPA-2788] Annotates events with Pod Name in the event of a Error type event

internal/chart/testdata/charts/dashboard-istio-cluster-issuer-pod-security-context.yaml, internal/chart/testdata/charts/dashboard-istio-cluster-issuer-volume-claim-templates.yaml, internal/chart/testdata/charts/dashboard-istio-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-istio.yaml, internal/chart/testdata/charts/dashboard-nginx-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-nginx.yaml, internal/chart/testdata/charts/dashboard-traefik-cluster-issuer-shipa.yaml, internal/chart/testdata/charts/dashboard-traefik-cluster-issuer.yaml, internal/chart/testdata/charts/dashboard-traefik.yaml, internal/templates/istio/yamls/certificate.yaml, internal/templates/istio/yamls/destinationRule.yaml, internal/templates/istio/yamls/gateway.yaml, internal/templates/istio/yamls/virtualService.yaml, internal/templates/nginx/yamls/certificate.yaml, internal/templates/nginx/yamls/ingress.yaml, internal/templates/traefik/yamls/certificate.yaml, internal/templates/traefik/yamls/http-ingress-route.yaml, internal/templates/traefik/yamls/https-ingress-routes.yaml
In order for some specific resource version to be target of patch, we want to add label to which deployment version each resource belongs
=> Add deployment version label to all resources

internal/deploy/deploy.go, internal/deploy/parameters.go, internal/deploy/parameters_test.go
This PR focuses on extra validation checks for volumes
1. A compliant k8 volume name (conforms to the following regex: `"[a-z0-9]([-a-z0-9]*[a-z0-9])?"`)
2. Explicitly checking that the pvc exists via a k8 call and erroring if it does not
=> [Shipa-2871] Adds volume name validators

internal/api/v1beta1/groupversion_info.go
As we are going to remove Framework completely from ketch,
we want to be able to add all the other types to scheme except
Framework.
=> Add SchemeOption to avoid registration of Framework and FrameworkList

config/crd/bases/theketch.io_apps.yaml, config/crd/bases/theketch.io_jobs.yaml, internal/api/v1beta1/app_types.go, internal/api/v1beta1/app_types_test.go, internal/api/v1beta1/job_types.go, internal/chart/testdata/render_yamls/annotations-patch.yaml, internal/chart/testdata/render_yamls/annotations-postrender.yaml, internal/controllers/app_controller.go, internal/controllers/app_controller_test.go, internal/controllers/job_controller.go
Permits overriding an App's namespace. Apps default to the namespace specified by `framework.spec.namespace`, but there are cases where we don't want namespace tied to framework.
=> Override app namespace

Dockerfile
tested on minikube --driver=qemu on M1 mach, arm64, image is pulled succesfully, but binary fails to run with error
```
exec /bin/agent: exec format error
```
this should fix it
=> Build platform independant go binary

internal/controllers/app_controller.go, internal/controllers/app_controller_test.go
=> [PLAY-751] fix canary deployment
